USE [MCN_Connect]
GO

/****** Object:  Table [dbo].[BAY_PKConstraints]    Script Date: 6/22/2022 7:30:32 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BAY_PKConstraints](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[tablename] [varchar](63) NULL,
	[cols] [varchar](255) NULL,
 CONSTRAINT [PK_BAY_PKConstraints] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


